# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweetbot', '0002_auto_20171029_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtweet',
            name='tweet',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
